### ISSUE TITLE
Wrong merged intervals with unsorted annotation

### ISSUE THREAD

**Issue by emi80** [guigolab/bamstats#23]
Stacktrace:
```
INFO[0000] Running bamstats 0.3.2-dev
INFO[0000] Using 8 out of 8 logical CPUs
INFO[0000] Creating index for gencode.v29lift37.annotation.nochr.gtf.gz
INFO[0005] Annotation scanned: 36 chromosomes found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x54e3cf]

goroutine 132 [running]:
github.com/guigolab/bamstats/annotation.(*Feature).Element(...)
        /home/emilio/workspace/bamstats/annotation/feature.go:96
github.com/guigolab/bamstats/annotation.updateIndex(0xc044112000, 0x0, 0x41054fe000000000, 0x630ddc, 0x4, 0x631f26, 0xa, 0x1, 0xc000084180, 0x0)
        /home/emilio/workspace/bamstats/annotation/annotation.go:192 +0x47f
github.com/guigolab/bamstats/annotation.createTree(0xc000084120, 0xc043b00ac0, 0xa, 0x41054fe000000000, 0xc055df4300, 0xc000019500, 0xc000084180)
        /home/emilio/workspace/bamstats/annotation/annotation.go:215 +0x12a
created by github.com/guigolab/bamstats/annotation.createIndex
        /home/emilio/workspace/bamstats/annotation/annotation.go:255 +0x268
```

**Comment by emi80** [comment]
This happens because the input interval slice is not sorted and `nil` elements are added when interleaving features
